### ISSUE TITLE
Отсутствует модуль Perl

### ISSUE THREAD

**Issue by backup112** [Litres/FB3Reader#22]
Здравствуйте!
Пытаюсь запустить конвертер:
https://github.com/Litres/FB3Reader/blob/master/DataProvider/AjaxGenerator/fb2json.pl

В строке 96 есть вызов функции
XPortal::Hyphenate::HyphString($Word);
В виду отсутствия модуля XPortal среди исходников - хотелось бы попросить вас описать какого типа данные возвращает эта функция. 
Ну или поместите лучше модуль с этой функции в исходники.

**Comment by gribuser** [comment]
Модуль коммитнул, в коде какие-то правки внес, но запускать не запускал, некогда. Если что не так поправьте, готов фикс вмержить

**Comment by backup112** [comment]
В принципе заработало, но в некоторых местах встречаются непонятные символы. Как это исправить?
![2015-07-22_083606](https://cloud.githubusercontent.com/assets/13435232/8817447/d0c9589a-304c-11e5-8223-18e7c792ef05.png)

**Comment by gribuser** [comment]
Возможно, версия перла другая, что-то с обработкой utf? На этом месте д.б. неразрывный пробел






Sent from Windows Mail





From: backup112
Sent: ‎Wednesday‎, ‎July‎ ‎22‎, ‎2015 ‎6‎:‎37‎ ‎AM
To: Litres/FB3Reader
Cc: 'Ð“Ñ€Ð¸Ð±Ð¾Ð² Ð”Ð¼Ð¸Ñ‚Ñ€Ð¸Ð¹'





В принципе заработало, но в некоторых местах встречаются непонятные символы. Как это исправить?
 2015-07-22_083606

**Comment by backup112** [comment]
perl v5.14.2

**Comment by gribuser** [comment]
Думаю, текущая версия в v5.14.2 должна работать, но сам не проверял пока, нету 5.14 под рукой

**Comment by backup112** [comment]
Как то странно - другие книги конвертит нормально... Плавающий баг вообщем.

**Comment by gribuser** [comment]
Давайте книгу, посмотрим. Может она просто убитая, на файлопомойках типа флибусты до 40% книг содержат немыслимый трэш

**Comment by backup112** [comment]
Использовал Ветхий Завет из примеров отсюда: https://github.com/Litres/FB3Reader/blob/master/DataProvider/AjaxExample/178297.fb2

**Comment by gribuser** [comment]
Ну не знаю. Проверил на 5.14.2 и 5.18.2 под Линукс - всё нормально генерится. Может, у вас LibXML старый или еще что-то в таком роде.

**Comment by gribuser** [comment]
Я бы предположил, что Encode надо обновить. Родной Encode в 5.14.2 совсем старый, возможно проблемы порождает именно он

**Comment by backup112** [comment]
Хорошо. Попробую.
А скажите, какой программой конвертером получить FB2 из EPUB с сохранением оглавления? В calibri из epub в FB2 например, оглавление не передается.

**Comment by gribuser** [comment]
Если бы из EPUB можно было получить FB2 с сохранением оглавления, нахрен бы вообще fb2 нужен был :)
Мы долгосрочно будем писать конвертер epub->fb3, который, hopefully, будет содержание выдирать с некой ненулевой вероятностью. Но даже если там вероятность будет 80% я уже фейрверк устрою и праздничный банкет. EPUB оконечный визуальный формат, извлечение из него структуры в общем случае задача нерешаемая, можно только костылей наставить для наиболее простых и частых случаев.

**Comment by backup112** [comment]
ОК. Спасибо за ответ. А подскажите тогда в какой программе лучше всего делать содержание в FB2 книге?

**Comment by gribuser** [comment]
Если коротко то Fiction Book Editor

Если длинно то здесь

https://docs.google.com/document/d/1gnNIKMM5haIxvOH_MYbDOBnRa8lJt6CGdibF7tBjsuA/edit

**Comment by backup112** [comment]
Спасибо!
