### ISSUE TITLE
Как в конце книги добавить кнопку купить?

### ISSUE THREAD

**Issue by backup112** [Litres/FB3Reader#23]
Есть метод в вашем скрипте: Site.prototype.showTrialEnd(ID)
Вопрос - как этот метод вызвать?

**Comment by samik3k** [comment]
Он автоматически движком вызывается, если в  JSON есть данные {i:"litres_trial_promo",t:"trialPurchase",xp:[2,6]}.
Тело метода можно прописать в FB3ReaderSite.js.
Там сейчас наблюдается public showTrialEnd(ID: string): string { return ''; }
ID нужен для навигации и рендеринга, примерно вот так выглядеть кнопка должна:
			return '<hr class="tag_empty-line" id="' + ID + '_0"/>' +
				'<div id="' + ID + '_1">' +
					'<p id="' + ID + '_1_0">' + text + '</p>' +
					'<hr class="tag_empty-line" id="' + ID + '_1_1"/>' +
					'<a id="' + ID + '_1_2" href="" class="trial-button">' + buttonText + '</a>' +
				'</div>';

**Comment by backup112** [comment]
А xp:[2,6] - это что за параметры?

**Comment by samik3k** [comment]
Попробую объяснить, это внешний XPath для навигации по книге.
Я не вижу чтоб этот pl конвертил и добавлял в конец последнего файла подобный тег.
В целом конец триала выглядит так:
{t:"p",xp:[2,5,413],c:["– ","…сво","­ему ","сер","­д","­цу."]},
{t:"p",xp:[2,5,414],c:["– ","Я ","сама ","была ","мо","­ло","­дой ","и ","знаю, ","где ","сей","­час ","на","­хо","­дит","­ся ","ее ","сер","­д","­це. ","Нет, ","я ","не ","жа","­лу","­юсь, ","я ","с ","удо","­воль","­с","­т","­ви","­ем ","сог","­ла","­си","­лась ","приг","­ля","­ды","­вать ","за ","пле","­мян","­ни","­цей, ","но ","это ","очень ","тя","­же","­ло. ","Ду","­маю, ","если ","бы ","ее ","мать, ","пус","­ть ","зем","­ля ","ей ","бу","­дет ","пу","­хом, ","была ","бы ","жива, ","она ","бес","­по","­ко","­илась ","бы ","мень","­ше, ","чем ","я. ","Это ","та","­кая ","от","­вет","­с","­т","­вен","­нос","­ть! ","Ки","­рилл…"]},
{i:"litres_trial_promo",t:"trialPurchase",xp:[2,6]}]

Большее кол-во элементов в массиве xp, большая вложенность текста. Подробней не расскажу.

**Comment by backup112** [comment]
Спасибо. Ясно.
Я так понял sub FlushFile{ подготавливает блок для записи
А WriteFinalJSONAnd { записывает в файл.
my $datastr = '['.join("\n",@DataToWrite).']'; - содержит массив который будем писать.
А цикл
while ($datastr =~ /hr:\s*\[\s*"#([^"]+)"\s*\]/sg){
		my $id = $1;
		unless ($id){
			# непонятная ссылка, пропустим
		} elsif (exists($HrefHash{$id})) {
			$datastr =~ s/(hr:\s*\[)\s*"#$id"\s*(\])/$1$HrefHash{$id}$2/gs;
			#warn "[OK] $id => ".$HrefHash{$id};
		} else {
			$NeedPatch{$FileN} ||= {f => $outfile, hr => {}};
			$NeedPatch{$FileN}->{hr}->{$id}++;
		}
	}
выдергивает данные в нужном формате.

Подскажите как определить что это последний файл и как в переменную my $datastr = '['.join("\n",@DataToWrite).']'; запихнуть еще и {i:"litres_trial_promo",t:"trialPurchase",xp:[2,6]} в конце если это последний файл?

**Comment by gribuser** [comment]
Последний параметр при запуске резалки - файл, из которого берется блок
"триальности". Я не помню сейчас точно, но мне кажется там и стандартно
ставиться блок, который стандартно возбуждает в читалке вызов события
"конец фрагмента". Т.е. вам надо либо просто на JS определить свой HTML-код
для конца триального фрашмента, либо в отрезалку фрагмента скормить
нестандартный для отрезалки, но стандартный для читалки блок, ну и, опять
же, определить каллбэк в сайте, который на место стандартной надписи "конец
фрагента" поставит ваш кастомный блок. На  ЛитРес мы там кнопку купить
ставим.
Точней про поседение резалки смогу сказать когда буду в офисе.

**Comment by backup112** [comment]
Я думаю проще в резалку в PERL скрипте добавлять сразу строку {i:"litres_trial_promo",t:"trialPurchase",xp:[2,6]}
А вы можете в https://github.com/Litres/FB3Reader/blob/master/DataProvider/AjaxGenerator/fb2json.pl
Добавить метод резалки?

**Comment by gribuser** [comment]
А смысл? Триалки так и так делает резалка, зачем ее функции перекладывать на кого-то?






Sent from Windows Mail





From: backup112
Sent: ‎Monday‎, ‎July‎ ‎27‎, ‎2015 ‎9‎:‎12‎ ‎AM
To: Litres/FB3Reader
Cc: 'Ð“Ñ€Ð¸Ð±Ð¾Ð² Ð”Ð¼Ð¸Ñ‚Ñ€Ð¸Ð¹'





Я думаю проще в резалку в PERL скрипте добавлять сразу строку {i:"litres_trial_promo",t:"trialPurchase",xp:[2,6]}
А вы можете в https://github.com/Litres/FB3Reader/blob/master/DataProvider/AjaxGenerator/fb2json.pl
Добавить метод резалки?

**Comment by backup112** [comment]
А резалка - это отдельный Perl скрипт у вас?
Я обрезку засунул в тот же скрипт fb2json.pl. Там в процессе записи оглавления удаляются сгенеренный JSON файлы лишние и все. Вот только как добавить строку {i:"litres_trial_promo",t:"trialPurchase",xp:[2,6]} еще не придумал... По идее открыть последний файл и заменить последнюю закрывающую скобку ] на {i:"litres_trial_promo",t:"trialPurchase",xp:[2,6]}] и все.
Может как то извращенно кажется, но на ум ничего проще не приходит...
Подскажите как вы это в резалке реализовали?

**Comment by samik3k** [comment]
Там есть уже обработчик, я совсем про него забыл. Надо в fb2 добавить доп тег.
В итоге в xsl есть:
&lt;xsl:template match="fb:section[@id = 'litres_trial_promo']">{chars:0,i:"litres_trial_promo",t:"trialPurchase",xp:[&lt;xsl:call-template name="reverse_id"/>]}&lt;xsl:if test="parent::fb:body/following-sibling::fb:body">,&lt;/xsl:if>&lt;xsl:text >&#010;&lt;/xsl:text>&lt;/xsl:template>
В конце fb2 у нас наблюдается:
&lt;section id="litres_trial_promo">
&lt;title>&lt;p>Конец ознакомительного фрагмента.&lt;/p>&lt;/title>
&lt;p>....&lt;/p>
&lt;/section>

**Comment by backup112** [comment]
Это делается в FBeditor?
или программно при генерации JSON?

**Comment by samik3k** [comment]
Добавьте в .fb2 чем угодно, хоть блокнотом.

**Comment by backup112** [comment]
Добавил эту секцию в блокноте) Сгенерил JSON. но там в последнем .js файле все равно не появился ничего похожего на {i:"litres_trial_promo",t:"trialPurchase",xp:[2,45,26]}

**Comment by samik3k** [comment]
А куда добавили? там надо было в "section" с текстом.

**Comment by backup112** [comment]
По разному пробовал добавить
<section id="litres_trial_promo">
<title><p>Конец ознакомительного фрагмента.</p></title>
<p>....</p>
</section>

Добавлял перед закрывающим тегом
 </body>

Пробовал добавить между секциями
  <p>избежать таких ошибок.</p>
  </section>
  <section>
   <title>
    <p>Заключение</p>
   </title>

Все равно - никакого эффекта(

**Comment by samik3k** [comment]
Там без &lt;section [b]id="litres_trial_promo"[/b]> не будет матчится xsl.
Найдите последнюю секцию с текстом, после добавьте что я выше писал.

**Comment by backup112** [comment]
Вот так добавлял, как очередную секцию
```
<section id="litres_trial_promo">
<title><p>Конец ознакомительного фрагмента.</p></title>
<p>....</p>
</section>
```

**Comment by backup112** [comment]
У вас обрезалка режет сам xml получается? Может я как то не верно обрезаю?

**Comment by samik3k** [comment]
Перловый скрипт обрабатывает fb2, матчит теги, переводит в json, затем тот же перл скрипт расставляет правильный xp везде. Затем уже режет на файлы. В отрывках fb2 уже есть секция с указанным id. Как именно его запускать не подскажу.

**Comment by backup112** [comment]
Получается нужно еще делать отрывок fb2 файла?

**Comment by samik3k** [comment]
У нас да, имеется 2 файла, один отрывок 25% с этим куском и целый 100% без этого куска, то есть не надо управлять выводом и созданием json элемента для кнопки, автоматически из fb2 получим.

**Comment by backup112** [comment]
Ясно все. Спасибо большое.
