### ISSUE TITLE
Добавление закладок на мобильном не работает?

### ISSUE THREAD

**Issue by backup112** [Litres/FB3Reader#24]
Здравствуйте!
Подскажите пожалуйста - я правильно понял, что на мобильном закладку добавить нельзя, а можно только посмотреть добавленные на компе?
И еще, по коду я на сколько понял синхронизация закладок идет в зависимости от сессии или нет?

**Comment by gribuser** [comment]
Закладки добавить можно везде, если вы про мобильную версию читалки ЛитРес, то там пока просто не выкатили GUI, на мобильном сильно выше требования.
Закладки синхронизируются по SID, да, пользователь должен быть авторизован на ЛитРес. Илаче как мы его с другого устройства опознаем, что с чем синхронизировать? Локально закладки и без этого сохраняются.

**Comment by backup112** [comment]
"на мобильном сильно выше требования"  - о каких требованиях вы говорите?
Закладки синхронизируются по SID - а какие методы для этого используются и в каком месте они подгружаются? я так понял из URL берется SID или из COOKIES. 
А сами закладки на стороне сервера получается тоже должны храниться? В каком виде и где?

**Comment by gribuser** [comment]
"о каких требованиях вы говорите"
Я говорю о требованиях к GUI

"А сами закладки на стороне сервера получается тоже должны храниться?"
Получается, что должны. Протокол работы с закладками описан в http://www.litres.ru/static/CataLitResAPI.zip

**Comment by backup112** [comment]
Благодарю!

Извините за оффтоп, но вы можете подсказать чем создаются m4b файлы? Какая программа под Windows позволяет такие файлы делать лучше всего?

**Comment by mediaexplorer74** [comment]
> http://www.litres.ru/static/CataLitResAPI.zip

Дмитрий, в ЛитРесе еще работаете? Выложите в опенсорс LitRes для WinMobile (UWP), пожалуйста. В ТП писал, толку НОЛЬ, ЛитРес ведет себя как собака на сене. 
- Поклонник древних фолиантов Люмия

**Comment by gribuser** [comment]
> Дмитрий, в ЛитРесе еще работаете?

Нет, я больше не работаю в ЛитРес :)

**Comment by mediaexplorer74** [comment]
> > Дмитрий, в ЛитРесе еще работаете?
> 
> Нет, я больше не работаю в ЛитРес :)

Ок. Ладно, сам смастерю софтинку на Xamarin Forms. C API уже разобрался, список книг получил.
